### PR TITLE
docs: Define user stories

### PR DESCRIPTION
**Pull request by oluwatobiss**
This PR adds "User Stories" to the glossary.

### CODE REVIEW

**Review by jdmedlock — CHANGES_REQUESTED** [review]
Thanks for making this suggestion @oluwatobiss. The classical definition of the user story is `As a <persona> I want <requirement> So I can <value-statement>`. This ensures that the user story focuses on the user and the value they will realize from a set of actions, rather than focusing on project management or technical terminology.

For example, `As an Idea Creator I want to provide the URLs to any supporting diagrams. URLs should have a plain text description in addition to the URL itself. So I can quickly and easily provide reviewers with more detail about my idea`.

I would prefer to use this classical definition rather than one that ties the User Story to an epic. Instead, I like to use dependencies to show the relationship between epics, stories, and tasks. For example, using parent-child relationships.

Here's the [Agile 101](https://github.com/chingu-voyages/Handbook/blob/main/docs/resources/projresources/agile101.md#agile-methodology-101) we provide to Chingu's in the Project Resources section of the Handbook.

Let me know what you think about this.

**Comment by oluwatobiss** [comment]
Thanks, @jdmedlock, for reviewing the PR and providing detailed feedback. I love the user-value focus of your suggestion. I will update the definition and resubmit.

**Comment by oluwatobiss** [comment]
I've updated the definition, @jdmedlock. Please let me know if it still needs some fine-tuning. Thanks.

**Review by jdmedlock — APPROVED** [review]
Thank you @oluwatobiss! Well done.

**Pull request merged**
