### PR TITLE
Feature: Add evaluation time expectation

### PR DESCRIPTION
**Pull request by jdmedlock**
For clarity added an explicit time limit for evaluation so Chingu's will understand how long they have to wait.

### CODE REVIEW

**Review by onetoughcookie226 — COMMENTED** [review]
So were was it saying that it is evaluated in 48 hrs?

**Comment by onetoughcookie226** [comment]
Anyway 2 business day is reasonable.

**Comment by jdmedlock** [comment]
> So were was it saying that it is evaluated in 48 hrs?

Expressing the deadline as two business days means we'll evaluate them within 48 hours during the work week, but the "clock" is stopped on Saturday, Sunday, and holidays. 

Do you think we should explicitly state this in in the Handbook?

**Comment by onetoughcookie226** [comment]
I don't think it's necessary. "2 business days" is clear, assuming everyone will consider timezone difference.

**Comment by cherylli** [comment]
It was in the end of the solo project form (google form) we should update that too

**Review by cherylli — APPROVED** [review]

**Comment by jdmedlock** [comment]
> It was in the end of the solo project form (google form) we should update that too

This is a great idea. I'll make sure it's updated today. Thanks

**Pull request merged**
